# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotosListTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire', '5.4.3'
  pod 'Kingfisher', '6.3.1'
  pod 'SwiftLint', '0.43.1'
  pod "TTGSnackbar", '1.10.5'
  pod 'SkeletonView', '1.26.0'
  pod 'UIImageColors', '2.1.0'

  # Pods for PhotosListTask

  target 'PhotosListTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotosListTaskUITests' do
    # Pods for testing
  end

end
